module.exports.getAst = function() {
    return `(Program
  (Block
    (Class
      (id Test)
      (Block
        (Func
          (id Test)
          (Parameters
            (id param1, default (1))
            (id param2, default (2))
            (id param3, default (3))
            (id param4, default (4))
          )
          (Block
            (=
              (IdExpression
                (.
                  (IdVariable
                    (this)
                  )
                  (IdVariable
                      (param1)
                    )
                )
              )
              (IdExpression
                (IdVariable
                  (param1)
                )
              )
            )
            (=
              (IdExpression
                (.
                  (IdVariable
                    (this)
                  )
                  (IdVariable
                      (param2)
                    )
                )
              )
              (IdExpression
                (IdVariable
                  (param2)
                )
              )
            )
            (=
              (IdExpression
                (.
                  (IdVariable
                    (this)
                  )
                  (IdVariable
                      (param3)
                    )
                )
              )
              (IdExpression
                (IdVariable
                  (param3)
                )
              )
            )
            (=
              (IdExpression
                (.
                  (IdVariable
                    (this)
                  )
                  (ConstId
                      (PARAM4)
                    )
                )
              )
              (IdExpression
                (IdVariable
                  (param4)
                )
              )
            )
          )
        )
        (Func
          (id getParam1)
          (Parameters)
          (Block
            (Return
              (IdExpression
                (.
                  (IdVariable
                    (this)
                  )
                  (IdVariable
                      (param1)
                    )
                )
              )
            )
          )
        )
        (Func
          (id setParam1)
          (Parameters
            (id newParam)
          )
          (Block
            (=
              (IdExpression
                (.
                  (IdVariable
                    (this)
                  )
                  (IdVariable
                      (param1)
                    )
                )
              )
              (IdExpression
                (IdVariable
                  (newParam)
                )
              )
            )
          )
        )
        (Func
          (id checkIfEqual)
          (Parameters
            (id paramX)
            (id paramY)
          )
          (Block
            (Return
              (==
                (IdExpression
                  (IdVariable
                    (paramX)
                  )
                )
                (IdExpression
                  (IdVariable
                    (paramY)
                  )
                )
              )
            )
          )
        )
        (Class
          (id Sub)
          (Block
            (Func
              (id Sub)
              (Parameters
                (id x)
                (id y)
                (id z)
              )
              (Block
                (=
                  (IdExpression
                    (.
                      (IdVariable
                        (this)
                      )
                      (IdVariable
                          (x)
                        )
                    )
                  )
                  (IdExpression
                    (IdVariable
                      (x)
                    )
                  )
                )
                (=
                  (IdExpression
                    (.
                      (IdVariable
                        (this)
                      )
                      (IdVariable
                          (y)
                        )
                    )
                  )
                  (IdExpression
                    (IdVariable
                      (y)
                    )
                  )
                )
                (=
                  (IdExpression
                    (.
                      (IdVariable
                        (this)
                      )
                      (IdVariable
                          (z)
                        )
                    )
                  )
                  (IdExpression
                    (IdVariable
                      (z)
                    )
                  )
                )
              )
            )
            (Func
              (id checkVariables)
              (Parameters
                (id var1)
              )
              (Block
                (Identifier Statement
                  (IdExpression
                    (IdVariable
                      (answer)
                    )
                  )
                )
                (If
                  (Case
                    (Condition
                      (!=
                        (IdExpression
                          (IdVariable
                            (var1)
                          )
                        )
                        (null)
                      )
                    )
                    (Body
                      (Block
                        (Match Expression
                          (IdExpression
                            (IdVariable
                              (var1)
                            )
                          )
                          (Matches
                            (Match
                              (1) ->
                              (Block
                                (=
                                  (IdExpression
                                    (IdVariable
                                      (answer)
                                    )
                                  )
                                  (one)
                                )
                              )
                            )
                            (Match
                              (2) ->
                              (Block
                                (=
                                  (IdExpression
                                    (IdVariable
                                      (answer)
                                    )
                                  )
                                  (two)
                                )
                              )
                            )
                            (Match
                              _ ->
                              (Block
                                (=
                                  (IdExpression
                                    (IdVariable
                                      (answer)
                                    )
                                  )
                                  (not one or two)
                                )
                              )
                            )
                          )
                        )
                      )
                    )
                  )
                )
                (Return
                  (IdExpression
                    (IdVariable
                      (answer)
                    )
                  )
                )
              )
            )
          )
        )
        (Class
          (id Collections)
          (Block
            (Func
              (id Collections)
              (Parameters
                (id dict)
                (id list)
                (id tup)
              )
              (Block
                (=
                  (IdExpression
                    (.
                      (IdVariable
                        (this)
                      )
                      (IdVariable
                          (dict)
                        )
                    )
                  )
                  (IdExpression
                    (IdVariable
                      (dict)
                    )
                  )
                )
                (=
                  (IdExpression
                    (.
                      (IdVariable
                        (this)
                      )
                      (IdVariable
                          (list)
                        )
                    )
                  )
                  (IdExpression
                    (IdVariable
                      (list)
                    )
                  )
                )
                (=
                  (IdExpression
                    (.
                      (IdVariable
                        (this)
                      )
                      (IdVariable
                          (tup)
                        )
                    )
                  )
                  (IdExpression
                    (IdVariable
                      (tup)
                    )
                  )
                )
              )
            )
            (Func
              (id addToDict)
              (Parameters
                (id id)
                (id value)
              )
              (Block
                (=
                  (IdExpression
                    ([]
                      (.
                        (IdVariable
                          (this)
                        )
                        (IdVariable
                            (dict)
                          )
                      )
                      (IdExpression
                        (IdVariable
                          (id)
                        )
                      )
                    )
                  )
                  (IdExpression
                    (IdVariable
                      (value)
                    )
                  )
                )
              )
            )
            (Func
              (id getDict)
              (Parameters
                (id id)
              )
              (Block
                (Return
                  (IdExpression
                    ([]
                      (.
                        (IdVariable
                          (this)
                        )
                        (IdVariable
                            (dict)
                          )
                      )
                      (IdExpression
                        (IdVariable
                          (id)
                        )
                      )
                    )
                  )
                )
              )
            )
            (Func
              (id getTuple)
              (Parameters)
              (Block
                (Return
                  (IdExpression
                    (.
                      (IdVariable
                        (this)
                      )
                      (IdVariable
                          (tup)
                        )
                    )
                  )
                )
              )
            )
          )
        )
      )
    )
  )
)`;
};
