module.exports.getAst = function() {
    return `(Program
  (Block
    (=
      (IdExpression
        (IdVariable
          (numbers)
        )
      )
      (List
        (VarList
          (1)
          (2)
          (3)
          (4)
          (5)
          (6)
        )
      )
    )
    (=
      (IdExpression
        (IdVariable
          (list)
        )
      )
      (List)
    )
    (Func
      (id count_by_two)
      (Parameters)
      (Block
        (=
          (IdExpression
            (IdVariable
              (result)
            )
          )
          (0)
        )
        (For id (i) in
          (IdExpression
            (IdVariable
              (numbers)
            )
          )
          (Block
            (If
              (Case
                (Condition
                  (==
                    (%
                      (IdExpression
                        (IdVariable
                          (i)
                        )
                      )
                      (2)
                    )
                    (0)
                  )
                )
                (Body
                  (Block
                    (+=
                      (IdExpression
                        (IdVariable
                          (result)
                        )
                      )
                      (IdExpression
                        (IdVariable
                          (i)
                        )
                      )
                    )
                  )
                )
              )
            )
          )
        )
        (Return
          (IdExpression
            (IdVariable
              (result)
            )
          )
        )
      )
    )
  )
)`;
}
