module.exports.getAst = function() {
    return `(Program
  (Block
    (If
      (Case
        (Condition
          (==
            (IdExpression
              (IdVariable
                (x)
              )
            )
            (true)
          )
        )
        (Body
          (Block
            (Return
              (true)
            )
          )
        )
      )
      (Else
        (Block
          (Return
            (false)
          )
        )
      )
    )
  )
)`;
}
